# Generated by Django 3.0.3 on 2020-02-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.ImageField(blank=True, upload_to='background_img')),
            ],
        ),
    ]
