# Generated by Django 3.0.3 on 2020-03-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_home', '0003_auto_20200301_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='category',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='category',
            field=models.ManyToManyField(to='modulo_home.Category'),
        ),
    ]
