# Generated by Django 3.0.3 on 2020-03-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_home', '0005_auto_20200301_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='created',
            field=models.DateField(default='2020-03-02'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(default='2020-03-02'),
        ),
    ]
